[package]
name = "calc_emd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emd = { git = "https://github.com/tanker-fund/rust-emd.git", tag = "v0.2.1" }